version: "3"
services:
  jenkins:
    build: .
    image: registry.cn-qingdao.aliyuncs.com/wangdali/codeforfun-jenkins
    container_name: jenkins
    environment:
      TZ: Asia/Shanghai
    networks:
      - codeforfun-net
    volumes:
      - "./data:/var/jenkins_home"
networks:
  codeforfun-net:
    external:
      name: codeforfun-network